// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThinClientApi.Data;

namespace ThinClientApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20181210195527_Init1")]
    partial class Init1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ThinClientApi.Models.ClientFile", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Checksum");

                    b.Property<string>("FileName");

                    b.Property<string>("Version");

                    b.HasKey("Id");

                    b.ToTable("ClientFiles");
                });

            modelBuilder.Entity("ThinClientApi.Models.Domain", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Domains");
                });

            modelBuilder.Entity("ThinClientApi.Models.RdpEndpoint", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("DomainId");

                    b.Property<int>("Port");

                    b.HasKey("Id");

                    b.HasIndex("DomainId");

                    b.ToTable("RdpEndpoints");
                });

            modelBuilder.Entity("ThinClientApi.Models.RdpEndpoint", b =>
                {
                    b.HasOne("ThinClientApi.Models.Domain", "Domain")
                        .WithMany("RdpEndpoints")
                        .HasForeignKey("DomainId");
                });
#pragma warning restore 612, 618
        }
    }
}
