// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThinClientApi.Data;

namespace ThinClientApi.Migrations
{
    [DbContext(typeof(ClientFileDbContext))]
    partial class ClientFileDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("ThinClientApi.Models.ClientFile", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FileName");

                    b.Property<string>("Version");

                    b.HasKey("Id");

                    b.ToTable("ClientFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
